### ISSUE TITLE
How to troubleshoot "------ Skipped Build: Project: MyProject ------"

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/visualstudio-docs#2923]
@gewarren 
Please see our conversation here: https://github.com/MicrosoftDocs/visualstudio-docs/commit/572312c5de220dc2e1615fc3edb7e0cb5b003cf6#commitcomment-32880142

"Can you please add documentation around how to debug "------ Skipped Build: Project: ------" messages in Visual Studio? MSBuild.exe has -fl (or -fileLogger) flag to log such messages, but I do not see a similar configuration in Visual Studio."

I believe most of the time this problem arises when the sln file is corrupted.

Related StackOverflow Q&A:

1. https://stackoverflow.com/questions/54038485/diagnosing-why-visual-studio-skips-building-a-project
2. https://stackoverflow.com/questions/1319772/how-to-determine-why-visual-studio-might-be-skipping-projects-when-building-a-so

**Comment by gewarren** [comment]
Topic question was originally asked on is here: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-specify-build-events-visual-basic?view=vs-2019

**Comment by jzabroski** [comment]
@gewarren Actually, I think it was the C# version of the same document, which seems out-of-sync with the Visual Basic one.  https://docs.microsoft.com/en-us/visualstudio/ide/how-to-specify-build-events-csharp?view=vs-2019

In particular, this warning/note was helpful but "not helpful enough":

> Pre-build events do not run if the project is up to date and no build is triggered.

In other words, I came to this web page for help because the first suggestion a coworker made when I was trying to figure out "Why is my project not building?" was to suggest adding a pre-build event.  However, the web page then told me, No, you can't use that for this.

It seems to me that a proper Call To Action is to say, you can't do that here, but we realize that's what most people expect, so here is how you do it.

**Comment by jzabroski** [comment]
By the way, my boss spent 2 days upgrading a solution and then rolled it back and gave up, and it turns out the root cause was a corrupt sln file where he accidentally removed a single F# project from a sln containing mostly C# projects.  I guess he did this with the intent of adding it back, but forgot to do so.

This is the second place I've worked where there's been a random F# project that gets called from a c# project and the whole experience is hard on most C# only developers who get stuck with it - I joined after it was built and am the only person who can read/write F#.

**Comment by ghogen** [comment]
Checking with the engineering team to see if it's possible to add diagnostic information on skipped projects.

**Comment by ghogen** [comment]
I added a section to the topic https://docs.microsoft.com/visualstudio/ide/how-to-exclude-projects-from-a-build. This covers skipped projects due to timestamp (up-to-date already), and skips due to build configuration.

**Comment by jzabroski** [comment]
It can also be skipped if the solution file dependencies Guids get jacked up

**Comment by rolandh** [comment]
Any way to resolve this? It keeps happening to people on my team, has collectively burnt a few days of dev time due to random projects being skipped for no reason with no warning.

**Comment by neobepmat** [comment]
Same issues for me, big solution only with C# projects. 
I have to admit that I've modified the solution file using `sed`:  anyway, some projects clean and build while others are "Skipped".
I'll be trying to dig on GUID as @jzabroski reported some msgs above.

**Comment by neobepmat** [comment]
GUIDs seem consistent.
Removing a "broken" project ad re-adding to the solution solves the "skipped project" issue.
Unfortunately, using this approach, refs to the project are removed.
Even if every project is under versioning control, "discard changes" must be applied for every broken project (and lot of projects  are separated repos).

**Comment by neobepmat** [comment]
For future reference, my issue has been solved applying this:
https://developercommunity.visualstudio.com/t/current-solution-contains-incorrect-configurations/1362048
```
Found how to fix this.

Wipe out all the GUID’s between this line:

GlobalSection(ProjectConfigurationPlatforms) = postSolution
Then go back into the .sln, build one time.

This will recreate all the entries again and the problem will go away.
```

**Comment by jzabroski** [comment]
Hi @neobepmat  - I recommend https://github.com/BlueMountainCapital/slopen for viewing solution files.  It's not a terribly fancy program - anyone with an intro to WPF class can understand what it does.  Unfortunately, it is for viewing only, and does not support buggy sln files.

Sln files stink.  If I prioritized it I would make a better sln file.  But honestly, only Visual Studio Big Brother cares about this stuff these days.  VS Code, you just give it a workspace.  And VS Code just has a lightweight  .vscode\settings.json to store your settings - much more intuitive than .suo files.

Junior developers who just use JetBrains Rider, dont even really know what a sln file is.

**Comment by sahin52** [comment]
I am still getting skipped without any warning:
```
2>------ Skipped Rebuild All: Project: Myprojects.DAL ------
2> 
========== Rebuild All: 1 succeeded, 0 failed, 1 skipped ==========
========== Rebuild completed at 11:10 and took 00,565 seconds ==========
```
No warning or anything. The project is not up-to-date and it is added in build configuration. 
Rebuild is not working for this project. **The only thing I can do is removing the project and adding again.**

**Comment by WilliamAntonRohm** [comment]
@all -- please consider these resources:
- Ask a question or find an answer on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/176/vs) page for Visual Studio.
- Check the [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio). 
- [Reddit](https://www.reddit.com/r/VisualStudio)
