### ISSUE TITLE
The Connected Services node in the solution is missing

### ISSUE THREAD

**Issue by eli191** [MicrosoftDocs/visualstudio-docs#5139]
What to do please when the Connected Services node in the solution is missing? On latest VS2019 for Mac. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6021f7a-f53d-b84d-702c-1bac79c6c213
* Version Independent ID: 086f8319-9834-4403-6140-348e3a0ed8f1
* Content: [Connected Services - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/connected-services?view=vsmac-2019)
* Content Source: [mac/connected-services.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/connected-services.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by sayedihashimi** [comment]
@eli191 are you working with a mobile project?

**Comment by eli191** [comment]
@sayedihashimi No, I am working on a .Net Core project (web application), which I want to link to a web service.

**Comment by muhammedmirzakilic** [comment]
I've same issue with :
Visual Studio Community 2019 for Mac
Version 8.5.1 (build 42)

**Comment by jmatthiesen** [comment]
Hello! This is an issue that should be fixed in an upcoming release as we increase support for Connected Services in ASP.NET Core projects. You can follow along with this item on our Developer Community site: https://developercommunity.visualstudio.com/content/problem/999064/connected-services-not-showing-up.html

**Comment by WilliamAntonRohm** [comment]
@jmatthiesen -- Jordan, thank you for your assistance.

**Comment by Boubalou** [comment]
We are now on build 41 and still not any fix regarding the missing node "Connected Services".  This is a deal-breaker for Mac developers if you ask me.

**Comment by WilliamAntonRohm** [comment]
cc @jmatthiesen for awareness

**Comment by jmatthiesen** [comment]
@Boubalou I don't recall the exact build number, but with v8.7 or later of Visual Studio for Mac you should be able to see the Connected Services node for ASP.NET Core projects. Have you tried one of the newer releases and do you see it there?

**Comment by Boubalou** [comment]
Actually, this is not a core project, that might be the issue there! We only have access to the node "Connected Services" under a Windows 10 development VM through Parallels Desktop. It works for our needs, but that is far from ideal.

**Comment by WilliamAntonRohm** [comment]
@Boubalou -- Mathieu, thank you for clarifying.  
- You are welcome to suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
