### ISSUE TITLE
Create an offline installation page does not discuss how to lock in a specific release

### ISSUE THREAD

**Issue by Mike4Online** [MicrosoftDocs/visualstudio-docs#6715]
My primary goal with establishing a cached network installation of Visual Studio 2019 Professional is so I can ensure all developer PCs obtain the same major.minor.servicing build (e.g. 16.9.5).  But this page does not mention any of the following:

1) How to obtain a specific older servicing release of Visual Studio 2019

2) How to configure Visual Studio 2019 on developer PCs so it always looks only to the cached network installation.  The article mentions special command line commands which can do this, but I want to configure Visual Studio's built-in upgrade detection mechanism to be looking at my network/cached installation only, rather than looking at the normal Micrsoft release channel.

3) Our Visual Studio 2019 installations use a very specific set of workloads and individual components.  Can you provide a complete reference for workloads and individual components, so I can prepare and use a cached network installation that meets our needs?  Otherwise, I may have to prepare a full 35 GB network installation (and I'd rather not do that if it can be helped).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by Mike4Online** [comment]
Just to clarify, when I try to update my existing Visual Studio 2019 professional build 16.9.4 installation to 16.9.5, using the 16.9.5 installer available at [https://docs.microsoft.com/en-us/visualstudio/releases/2019/history](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history), the installation ultimately fails with an error saying an even newer build (16.10.0, which I do not want) is available (see attached).

**I was able to resolve this** by running the downloaded installer for VS 2019 Pro build 16.9.5 and adding the command line parameter `--noUpdateInstaller`, which is documented on page [https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019).  This parameter should be prominently mentioned on the [https://docs.microsoft.com/en-us/visualstudio/releases/2019/history](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history) page.  it should also be prominently mentioned that the upgrade will successfully install the specified build (in my case 16.9.5) and then prompt to upgrade fuirther to the latest build (16.10.0).  This latter upgrade can be canceled.

I found the page which describes how to add workloads and components to a **response.json** file, at [https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019).

What is not clear from the documentation is if I have already installed Visual Studio 2019 Professional build 16.9.4 on several workstations, using the regular web installer, how do I go back and configure those installations to subsequently look only to my newly-established network-based installation for updates  (i.e. to force updating to 16.9.5, rather than to 16.10.0)?

I found some registry settings at [https://docs.microsoft.com/en-us/visualstudio/install/set-defaults-for-enterprise-deployments?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/install/set-defaults-for-enterprise-deployments?view=vs-2019), but this page presents a ton of information, and it is not readily apparent if an existing Visual Studio installation done with the regular web installer can be reconfigured to look to a network installation for its updates.

**Comment by WilliamAntonRohm** [comment]
@Mike4Online -- Michael, thank you for your well-researched feedback.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@j-martens -- Josée, please look into this issue.

**Comment by anandmeg** [comment]
#reassign: @anandmeg

**Comment by anandmeg** [comment]
@Mike4Online, thank you for your feedback. We've updated our docs recently to add/clarify information on these areas.

- [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022)
- [Create a network-based installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2022)
- [Use command-line parameters to install Visual Studio ](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022)

Please let us know if you have any other feedback. Thanks again for your feedback!

**Comment by Mike4Online** [comment]
> I was able to resolve this by running the downloaded installer for VS 2019 Pro build 16.9.5 and adding the command line parameter` --noUpdateInstaller`, which is documented on page [https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019). This parameter should be prominently mentioned on the [https://docs.microsoft.com/en-us/visualstudio/releases/2019/history](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history) page.

The `--noUpdateInstaller` parameter is still not mentioned anywhere on the [https://docs.microsoft.com/en-us/visualstudio/releases/2019/history](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history) page.

This parameter is mentioned on the [https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022) page, but its description does not mention how essential this parameter is when installing an older release that was downloaded from the History page.  

So it is still very likely those who download older Visual Studio installers will run them without the `--noUpdateInstaller` parameter, leading to the installer updating itself and installing the wrong (newer) version of Visual Studio.

**Comment by christineruana** [comment]
Hi @Mike4Online - Thank you very much for your feedback and suggestions.  I think I understand what you're trying to do - create a network layout of a particular version of Visual Studio and have your client machines use that to acquire updates.  Right?

Over the past six months we've made a lot of improvements to this layout and updating functionality, and I just got done updating all of the online documentation a couple weeks ago.  I see from your comments immediately above that you read thru the revised "[Create a Network Install](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019)" documentation which discusses how to create, update, and maintain a network layout, as well as how to to the initial client install from this network layout.  The "[Update a VS client that was installed from a network layout](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio)" page discusses keeping the client updated, and the "[Programmatically configure default settings using a response file](https://docs.microsoft.com/en-us/visualstudio/install/automated-installation-with-response-file?view=vs-2019)" discusses setting the client's source location for updates. 

Regarding your suggestion to "pin" the installer to a static older version by using the --noUpdateInstaller flag... that is really not the right approach.  The purpose of that flag was to prevent the installer from trying to update if the client doesn't have access to the internet.  We really don't recommend keeping the installer static, as that may prevent the client from getting security updates or bug fixes that we put in the installer.  The installer is a separate app than the Visual Studio product, and we actually recommend to --useLatestInstaller to keep your Visual Studio client instances updated!  

If you want to configure your clients to look at your layout for the updates, then you need to ensure that the channelURI value on the client is set correctly.  With VS 2019 this value was hard to change once it was initially set upon client install, but we recently made a lot of improvements in this space.  Using the VS 2022 installer, you can leverage this functionality with your VS 2019 layouts if you the --useLatestInstaller param.  I documented how to do this here:  https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019#ensure-your-layout-is-using-the-latest-installer.   

We do have a bug that will be fixed in January where sometimes the fixed link bootstrappers aren't updating client instances properly.  I think this bug may be the root cause as to why you searched for and found the --noUpdateInstaller workaround.   However, we must deliver a fix for the bug too.  If you want to open a [Developer Community feedback bug](https://aka.ms/vs/admin/feedback) about this update problem, I can hook it to the bug and you'll be notified when the fix is released.

Meanwhile, please re-read the section about configuring the channelURI on your clients using the VS 2022 installer and keeping your layouts updated with the --useLatestInstaller flag.  I think that's the solution that you should embrace.  Really want to see you be successful here so feel free to continue reaching out to us with question.  It's probably best, though, to file a DevCommunity bug to work through this.  In the bug, please mention layouts and updates and it'll get to the right team.  You can tag me here with the link too.  That system is more setup to handle interactive feedback, as this one sat here for a while.  Apologize for the delay and really want to get this working for you.  Again, really appreciate the feedback as it'll help us make this whole scenario better for all involved.     

-Christine

**Comment by Mike4Online** [comment]
Hello @christineruana - thanks for your detailed response.  I'll read through the links you've provided regarding channelURI's and setting up a network installation.

As for installing a specific older build of Visual Studio directly, using an installer downloaded from the Visual Studio History page, you responded with:

> Regarding your suggestion to "pin" the installer to a static older version by using the --noUpdateInstaller flag... that is really not the right approach. The purpose of that flag was to prevent the installer from trying to update if the client doesn't have access to the internet. We really don't recommend keeping the installer static, as that may prevent the client from getting security updates or bug fixes that we put in the installer. The installer is a separate app than the Visual Studio product, and we actually recommend to --useLatestInstaller to keep your Visual Studio client instances updated!

I agree that allowing the installer to update itself makes sense when you are trying to install the latest version of Visual Studio.
But if you are trying to install _a specific version_ of Visual Studio -- say one that was released three months ago rather than the very latest release -- then allowing the installer to update itself will then cause the install to install the very latest version of Visual Studio.  Put another way, if you download a particular Visual Studio Installer (from the Visual Studio history page) for a build that is not the very latest, and you run this installer without specifying `--NoUpdateInstaller`, then the installer will update itself to the latest version and then proceed to install the latest Visual Studio -- which is not what you're trying to do.  It is also not intuitive for the end user, who must know to specify `--NoUpdateInstaller`.

So if my approach is not correct when trying to install a specific, older build of Visual Studio, then what would be the correct approach?  This is assuming I am NOT trying to do a network install but rather using the older VS installer downloaded from the Visual Studio History page and running that installer directly.  Is there a way to let the installer update itself to the latest version and still install a specific older build of Visual Studio?

Thanks.

**Comment by christineruana** [comment]
Hi @Mike4Online,

I just wanted to let you know that we shipped updates today that fixed a problem that prevented updating a client install from one fixed link version to another fixed link version using different (subsequent) bootstrappers that are on the release history page.  I think you may have been inadvertently running into this problem which is what forced you to discover and use the --noUpdateInstaller parameter.  Using that parameter should never be necessary because we  really want people on the latest installer.  The "fixed link" bootstrappers that you find on this page: https://docs.microsoft.com/en-us/visualstudio/releases/2019/history are supposed to install that very particular version of the product, but the bug was preventing this from working properly).  

To address your very last question above, it *is* possible to have the latest installer installed, but still install a particular *older* version of the product using one of the fixed link bootstrappers.  The bootstrappers all have the concept of a "minimum" required installer, but they don't have the concept of a "maximum" required installer.  The "minimum" required installer is the installer that was considered current when that version of the product was built.  The bug we just fixed was confusion around the "minimum" and "current" concepts.  The installer is a singleton, meaning that there is only one (our preference is the latest one) installed on the machine at any given time. Conversely, there can be multiple versions of Visual Studio installed on the machine at any given time.  TBH, I actually recommend passing in the --useLatestInstaller flag, which will  grab the VS 2022 installer.   

To receive the benefits of the bug fix we just shipped, your install (or update) has to be at least using a Jan 2022 or higher bootstrapper.  Then, any subsequent update using any more recent (i.e. post Jan 2022) bootstrapper should just always work.  

Can you please try this out and confirm that it's all working for you?  Please let me know if you run into further troubles.  Always appreciate feedback here too:   https://developercommunity.visualstudio.com/report?entry=suggestion&space=8 

Thanks,  
        Christine

**Comment by christineruana** [comment]
#reassign: @christineruana

**Comment by Mike4Online** [comment]
@christineruana , thanks for following up.  Glad to see the behavior I was experiencing was due to a bug, and that it is fixed for Visual Studio 2022 installers going forward.

I'll follow your advice in allowing these version-specific installers to update themselves to the latest version of Visual Studio installer, while still installing the version of Visual Studio they were intended to install.

This resolves my need - I no longer have to establish an offline installation or take other measures to work around this issue.  Feel free to close this GitHub issue.

**Comment by j-martens** [comment]
Thank you!!


#please-close

**Comment by Mike4Online** [comment]
@j-martens , this issue appears to be already closed.
