### ISSUE TITLE
Vs 2022 for Mac Github Setup

### ISSUE THREAD

**Issue by paulleblanc** [MicrosoftDocs/visualstudio-docs#8283]
How does one go about creating or copying a GitHub repository in Visual Studio 2022 for Mac? The docs keep referencing a 'Version Control' menu which doesn't even exist in the latest version of Visual Studio. The inability to integrate with GitHub makes this release essentially unusable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 606d4c70-3daf-8b03-9c31-b690927a7136
* Version Independent ID: 24a13aaf-3d14-c810-182c-2c2d93fc299b
* Content: [Setting up a Git Repository - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/set-up-git-repository?view=vsmac-2022#clone-an-existing-repository)
* Content Source: [mac/set-up-git-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/set-up-git-repository.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by WilliamAntonRohm** [comment]
@paulleblanc -- Paul, thank you for your feedback.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Stack Overflow](https://stackoverflow.com/search?q=%22visual+studio%22)  
- [Reddit](https://www.reddit.com/r/VisualStudio)

@jmatthiesen -- Jordan, please look into this issue.

**Comment by jmatthiesen** [comment]
@paulleblanc - thanks for the feedback. I just updated our documentation for the Visual Studio 2022 for Mac release, which moved to a Git menu in the IDE instead of a Version Control menu. I hope this helps!

https://docs.microsoft.com/en-us/visualstudio/mac/set-up-git-repository?view=vsmac-2022

**Comment by jmatthiesen** [comment]
#please-close

**Comment by skima74** [comment]
No, this doesn't help at all.
The issue not addressed by the documentation is github authentication.
The application asks for a username and "password" - this already is erroneous as the application will not work with the github password, it requires a Personal access token (PAT).
To make matters worse, once you have submitted your password, and the operation fails, there is no way via the IDE to reset the password. Nor is there any mention of it in any documentation.
After much digging around one finally finds instruction on how to remove the password from the osx key chain, and again after searching public forums one can stitch together how to get the PAT from github, and then try again.
Hard to imagine a worse first impression of the product is possible.

**Comment by mattgenious** [comment]
@jmatthiesen and @WilliamAntonRohm as @skima74 writes, this doesn't solve the problem that Visual Studio 2022 for Mac is attempting to connect to Github using an authentication method that Github does not support.
```
Git failed with a fatal error.
ExitCode : 128
Pushing to https://github.com/[REDACTED].git
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/[REDACTED].git/'
```

As far as I can see Visual Studio 2022 does not support using SSH with the built in Git controls, therefore users of Visual Studio 2022 cannot use the built in Git controls with Github repositories.

**Comment by Lisa12n** [comment]
I have the same problem. Any solutions forthcoming?

**Comment by sevoku** [comment]
@skima74, @Lisa12n, @andyjohnson0 Currently VS for Mac does not support 2FA with Github, but authenticating using a PAT (create a PAT and paste it into the password field) or SSH should just work. If it doesn't please report it using the "Help > Report a Problem…" menu right after reproducing the issue so it'd also submit the logs for us to better understand what's going wrong. Thanks!

**Comment by skima74** [comment]
It does work, but both the App and the Docs specify the use of the GitHub “password” which is a misdirection and wastes eveyone’s time. At a bare minimum someone should  fix the docs or better yet the actual app prompt. On 4 Jan 2023, at 1:59 am, Vsevolod Kukol ***@***.***> wrote:﻿
@skima74, @Lisa12n, @andyjohnson0 Currently VS for Mac does not support 2FA with Github, but authenticating using a PAT (create a PAT and paste it into the password field) or SSH should just work. If it doesn't please report it using the "Help > Report a Problem…" menu right after reproducing the issue so it'd also submit the logs for us to better understand what's going wrong. Thanks!

**Comment by kilngod** [comment]
The GitHub integration with Visual Studio 2022 Mac has sucked forever as is the bane of my existence. I kind of get by using GitHub desktop on the Mac but that tends to pull in a lot of unwanted files into version control. I'm still shocked this is not working and there is no easy way to reset authentication for GitHub from within VS2022 mac?

**Comment by Hkairon98** [comment]
> https://docs.microsoft.com/en-us/visualstudio/mac/set-up-git-repository?view=vsmac-2022

if u found any solution plz revert
